# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'demo_music' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for demo_music
    pod 'YYKit'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'BlocksKit'
    pod 'MLTransition'
    pod 'MBProgressHUD'
    pod 'WMPageController'
    pod 'iCarousel'
end
